# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frm_Note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frm_Note(object):
    def setupUi(self, Frm_Note):
        Frm_Note.setObjectName("Frm_Note")
        Frm_Note.resize(524, 348)
        Frm_Note.setMinimumSize(QtCore.QSize(524, 348))
        Frm_Note.setMaximumSize(QtCore.QSize(524, 348))
        self.pushButton = QtWidgets.QPushButton(Frm_Note)
        self.pushButton.setGeometry(QtCore.QRect(420, 310, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lbl_Titulo = QtWidgets.QLabel(Frm_Note)
        self.lbl_Titulo.setGeometry(QtCore.QRect(12, 12, 500, 36))
        self.lbl_Titulo.setMinimumSize(QtCore.QSize(500, 36))
        self.lbl_Titulo.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_Titulo.setFont(font)
        self.lbl_Titulo.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.lbl_Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Titulo.setObjectName("lbl_Titulo")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Frm_Note)
        self.plainTextEdit.setGeometry(QtCore.QRect(13, 56, 500, 250))
        self.plainTextEdit.setMinimumSize(QtCore.QSize(500, 250))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Frm_Note)
        QtCore.QMetaObject.connectSlotsByName(Frm_Note)

    def retranslateUi(self, Frm_Note):
        _translate = QtCore.QCoreApplication.translate
        Frm_Note.setWindowTitle(_translate("Frm_Note", "Dialog"))
        self.pushButton.setText(_translate("Frm_Note", "Guardar"))
        self.lbl_Titulo.setText(_translate("Frm_Note", "[Comentario estacion]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frm_Note = QtWidgets.QDialog()
    ui = Ui_Frm_Note()
    ui.setupUi(Frm_Note)
    Frm_Note.show()
    sys.exit(app.exec_())
